image: maven:3.9.6

variables:
  MAVEN_CLI_OPTS: "-Dgitlab.username=$GITLAB_USERNAME -Dgitlab.password=$GITLAB_PASSWORD -Dhighgeekmaven.username=$HIGHGEEKMAVEN_USERNAME -Dhighgeekmaven.password=$HIGHGEEKMAVEN_PASSWORD -s maven_settings.xml --batch-mode"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - main
