#Redis
redis-ip: "127.0.0.1"
redis-port: "6379"
#Mysql
db-connectionstring: "jdbc:mysql://localhost:3306/db"
db-username: "root"
db-password: ""
#Chat
servername: ""
prettyservername: ""
#ServerList
serverlistpos: 10
serverlistvisible: true
