
settings:
  language: "en_EN" # Which language should be used, valid language is at the moment en_EN (English).

#
# chat
#

chat:
  servername: "servername"
  listentodiscord: false


#
# MySQL
#

mysql:
  host: "127.0.0.1"
  port: "3306"
  database: "mcserver_datadb"
  username: "root"
  password: "abahanama420"
  synctablename: "sync_player_data_table"
  virtualinventorytablename: "sync_redis_data_table"


#
# Redis
#

redis:
  host: "10.220.22.126"
  database: "1"
  username: "root"
  password: "st"
  port: "6379"

#
# Version
# - This is needed for Updating the Plugin right, so don't remove or edit it!
#

version: ${project.version}
