#########################################
#                                       #
#     Config from MySQL-Sync Plugin     #
#        Coded by Leo Schneider         #
#                                       #
#########################################
#
# NOTICE:
# - For /sync reload you will need to set the Player the following Permission "sync.reload"
#
# Settings
# - Everything is described.
#

settings:
  storageType: MYSQL # Which Database should be used to Sync data, valid entries, MONGODB and MYSQL
  usingOldData: true # If existing data of Player which is saved in the World should be used to generate the Players Database Profile
  syncing:
    inventory: true # Syncing Inventory between the Servers
    enderchest: true # Syncing EnderChest between the Servers
    exp: true # Syncing EXP between the Servers
    gamemode: true # Syncing GameMode between the Servers
    hunger: true # Syncing Hunger between the Servers
    health: true # Syncing Health between the Servers
    effects: true # Syncing Potion Effects between the Servers
    advancements: true # Syncing ALL Advancements between the Servers (This requires a large MySQL because Minecraft Advancements are giant!)
    statistics: true # Syncing ALL Statistics between the Servers (This requires a large MySQL because Minecraft Statistics are way bigger than the Advancements, and even they are giant!)
  sending:
    generated: true # Sending generated Message to Player
    error: true # Sending Error Message to the Player
  onlySyncPermission: false # Only Sync the Players Data with the permission "sync.sync"
  usePermission: false # You will need to set the Player the following Permission for the /sync command: "sync.command" (Players still need "sync.reload" to reload the Config)
  language: "en_EN" # Which language should be used, valid languages are at the moment, en_EN (English) and de_DE (German) or if you add a own language in the lang folder.
  backup: # Backups of data are needed if the server may crash. If you disable it, data will be lost after a crash of the server.
    enabled: true # Set false to disable Backups of data and true to enable Backups of data.
    backupCycle: 1200 # The Cycle in which the plugin should Backup data, the time must be in ticks (1200 Ticks are 1 Minute)
    values:
      inventory: true # If the Inventory of the Player should be backed up.
      enderchest: true # If the Enderchest of the Player should be backed up.
      exp: true # If the EXP of the Player should be backed up.
      gamemode: true # If the Gamemode of the Player should be backed up.
      hunger: true # If the Hunger of the Player should be backed up.
      health: true # If the Health of the Player should be backed up.
      effects: false # If the Effects of the Player should be backed up.
      advancements: false # If the Advancements of the Player should be backed up.
      statistics: false # If the Statistics of the Player should be backed up.

#
# chat
#

chat:
  servername: "survivalprivate1-node1"
  listentodiscord: false


#
# MySQL
#

mysql:
  host: "127.0.0.1"
  port: "3306"
  database: "mcserver_datadb"
  username: "root"
  password: "abahanama420"
  synctablename: "sync_player_data_table"
  virtualinventorytablename: "sync_redis_data_table"


#
# Redis
#

redis:
  host: "10.220.22.126"
  database: "1"
  username: "root"
  password: "st"
  port: "6379"

#
# Version
# - This is needed for Updating the Plugin right, so don't remove or edit it!
#

version: ${project.version}
