package eu.highgeek.highgeeksync.data.sql.entities;
// Generated 31. 1. 2025 17:04:56 by Hibernate Tools 4.0.1.Final


import org.hibernate.annotations.NamedQuery;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VirtualInventories generated by hbm2java
 */
@NamedQuery(
        name = "VirtualInventories.findAll",
        query = "SELECT p FROM virtual_inventories p"
)
@NamedQuery(
        name = "VirtualInventories.findByUUID",
        query = "SELECT p FROM virtual_inventories p WHERE p.inventory_uuid = :inventory_uuid"
)
@Entity
@Table(name="virtual_inventories"
    ,catalog="mcserver_maindb"
)
public class VirtualInventories  implements java.io.Serializable {


     private String inventoryUuid;
     private String playerUuid;
     private String playerName;
     private String inventoryName;
     private Integer size;
     private Boolean web;
     private String jsondata;
     private String lastUpdated;

    public VirtualInventories() {
    }

	
    public VirtualInventories(String inventoryUuid) {
        this.inventoryUuid = inventoryUuid;
    }
    public VirtualInventories(String inventoryUuid, String playerUuid, String playerName, String inventoryName, Integer size, Boolean web, String jsondata, String lastUpdated) {
       this.inventoryUuid = inventoryUuid;
       this.playerUuid = playerUuid;
       this.playerName = playerName;
       this.inventoryName = inventoryName;
       this.size = size;
       this.web = web;
       this.jsondata = jsondata;
       this.lastUpdated = lastUpdated;
    }
   
     @Id 

    
    @Column(name="inventory_uuid", unique=true, nullable=false, length=100)
    public String getInventoryUuid() {
        return this.inventoryUuid;
    }
    
    public void setInventoryUuid(String inventoryUuid) {
        this.inventoryUuid = inventoryUuid;
    }

    
    @Column(name="player_uuid", length=100)
    public String getPlayerUuid() {
        return this.playerUuid;
    }
    
    public void setPlayerUuid(String playerUuid) {
        this.playerUuid = playerUuid;
    }

    
    @Column(name="player_name", length=16)
    public String getPlayerName() {
        return this.playerName;
    }
    
    public void setPlayerName(String playerName) {
        this.playerName = playerName;
    }

    
    @Column(name="inventory_name", length=100)
    public String getInventoryName() {
        return this.inventoryName;
    }
    
    public void setInventoryName(String inventoryName) {
        this.inventoryName = inventoryName;
    }

    
    @Column(name="size")
    public Integer getSize() {
        return this.size;
    }
    
    public void setSize(Integer size) {
        this.size = size;
    }

    
    @Column(name="web")
    public Boolean getWeb() {
        return this.web;
    }
    
    public void setWeb(Boolean web) {
        this.web = web;
    }

    
    @Column(name="jsondata")
    public String getJsondata() {
        return this.jsondata;
    }
    
    public void setJsondata(String jsondata) {
        this.jsondata = jsondata;
    }

    
    @Column(name="last_updated")
    public String getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(String lastUpdated) {
        this.lastUpdated = lastUpdated;
    }




}


